version: "3"

dotenv: [".env"]

tasks:
  run-server:
    desc: run standalone Twilio HTTP server
    dir: ./
    env:
      PYTHONPATH: "{{.PWD}}:{{.PYTHONPATH}}"
    cmds:
      - python3 server/main.py

  run-gd-server:
    desc: run tman dev http server for TMAN Designer
    dir: ./tenapp
    cmds:
      - tman designer

  install:
    desc: install dependencies
    dir: ./tenapp
    cmds:
      - tman install

  build:
    desc: build
    dir: ./tenapp
    cmds:
      - tman run build

  run:
    desc: run servers
    deps:
      - task: run-server
      - task: run-gd-server