version: "3"

dotenv: [".env"]

tasks:
  run-server:
    desc: run backend http server
    dir: ./
    cmds:
      - tman run twilio-server

  run-gd-server:
    desc: run tman dev http server for TMAN Designer
    dir: ./
    cmds:
      - tman designer

  run:
    desc: run servers
    deps:
      - task: run-server
      - task: run-gd-server